// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250216165358_Fifth-migration")]
    partial class Fifthmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Description = "Basic greetings",
                            Title = "Greetings"
                        },
                        new
                        {
                            CourseId = 2,
                            Description = "Counting from 1 to 10",
                            Title = "Numbers"
                        },
                        new
                        {
                            CourseId = 3,
                            Description = "Daily conversations",
                            Title = "Common Phrases"
                        },
                        new
                        {
                            CourseId = 4,
                            Description = "Ordering in a café",
                            Title = "Food & Drinks"
                        },
                        new
                        {
                            CourseId = 5,
                            Description = "Asking for directions",
                            Title = "Directions"
                        },
                        new
                        {
                            CourseId = 6,
                            Description = "Buying things and transactions",
                            Title = "Shopping"
                        },
                        new
                        {
                            CourseId = 7,
                            Description = "Telling time and discussing dates",
                            Title = "Time & Dates"
                        },
                        new
                        {
                            CourseId = 8,
                            Description = "Useful phrases for traveling",
                            Title = "Travel"
                        },
                        new
                        {
                            CourseId = 9,
                            Description = "Professional conversations",
                            Title = "Work & Business"
                        },
                        new
                        {
                            CourseId = 10,
                            Description = "Asking for help and emergency",
                            Title = "Emergency Situations"
                        });
                });

            modelBuilder.Entity("WebApi.Models.CourseCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("EnglishText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NorwegianText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            EnglishText = "Hello",
                            NorwegianText = "Hallo"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            EnglishText = "Hi",
                            NorwegianText = "Hei"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            EnglishText = "Good morning",
                            NorwegianText = "God morgen"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            EnglishText = "Good afternoon",
                            NorwegianText = "God ettermiddag"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            EnglishText = "Good evening",
                            NorwegianText = "God kveld"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 1,
                            EnglishText = "Good night",
                            NorwegianText = "God natt"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 1,
                            EnglishText = "How are you?",
                            NorwegianText = "Hvordan har du det?"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 1,
                            EnglishText = "I’m fine, thank you",
                            NorwegianText = "Jeg har det bra, takk"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 1,
                            EnglishText = "What’s your name?",
                            NorwegianText = "Hva heter du?"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 1,
                            EnglishText = "My name is...",
                            NorwegianText = "Jeg heter..."
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 2,
                            EnglishText = "One",
                            NorwegianText = "En"
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 2,
                            EnglishText = "Two",
                            NorwegianText = "To"
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 2,
                            EnglishText = "Three",
                            NorwegianText = "Tre"
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 2,
                            EnglishText = "Four",
                            NorwegianText = "Fire"
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 2,
                            EnglishText = "Five",
                            NorwegianText = "Fem"
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 2,
                            EnglishText = "Six",
                            NorwegianText = "Seks"
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 2,
                            EnglishText = "Seven",
                            NorwegianText = "Sju"
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 2,
                            EnglishText = "Eight",
                            NorwegianText = "Åtte"
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 2,
                            EnglishText = "Nine",
                            NorwegianText = "Ni"
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 2,
                            EnglishText = "Ten",
                            NorwegianText = "Ti"
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 3,
                            EnglishText = "Hello",
                            NorwegianText = "Hei"
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 3,
                            EnglishText = "Good morning",
                            NorwegianText = "God morgen"
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 3,
                            EnglishText = "Good night",
                            NorwegianText = "God natt"
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 3,
                            EnglishText = "How are you?",
                            NorwegianText = "Hvordan har du det?"
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 3,
                            EnglishText = "I'm fine, thank you",
                            NorwegianText = "Jeg har det bra, takk"
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 3,
                            EnglishText = "What is your name?",
                            NorwegianText = "Hva heter du?"
                        },
                        new
                        {
                            Id = 27,
                            CourseId = 3,
                            EnglishText = "My name is...",
                            NorwegianText = "Jeg heter..."
                        },
                        new
                        {
                            Id = 28,
                            CourseId = 3,
                            EnglishText = "Nice to meet you",
                            NorwegianText = "Hyggelig å møte deg"
                        },
                        new
                        {
                            Id = 29,
                            CourseId = 3,
                            EnglishText = "See you later",
                            NorwegianText = "Sees senere"
                        },
                        new
                        {
                            Id = 30,
                            CourseId = 3,
                            EnglishText = "Goodbye",
                            NorwegianText = "Ha det"
                        },
                        new
                        {
                            Id = 31,
                            CourseId = 4,
                            EnglishText = "I would like a coffee, please",
                            NorwegianText = "Jeg vil gjerne ha en kaffe, takk"
                        },
                        new
                        {
                            Id = 32,
                            CourseId = 4,
                            EnglishText = "Do you have a menu?",
                            NorwegianText = "Har dere en meny?"
                        },
                        new
                        {
                            Id = 33,
                            CourseId = 4,
                            EnglishText = "I am allergic to...",
                            NorwegianText = "Jeg er allergisk mot..."
                        },
                        new
                        {
                            Id = 34,
                            CourseId = 4,
                            EnglishText = "Can I have the bill, please?",
                            NorwegianText = "Kan jeg få regningen, takk?"
                        },
                        new
                        {
                            Id = 35,
                            CourseId = 4,
                            EnglishText = "What do you recommend?",
                            NorwegianText = "Hva anbefaler du?"
                        },
                        new
                        {
                            Id = 36,
                            CourseId = 4,
                            EnglishText = "I’ll have the same",
                            NorwegianText = "Jeg tar det samme"
                        },
                        new
                        {
                            Id = 37,
                            CourseId = 4,
                            EnglishText = "A table for two, please",
                            NorwegianText = "Et bord for to, takk"
                        },
                        new
                        {
                            Id = 38,
                            CourseId = 4,
                            EnglishText = "I am hungry",
                            NorwegianText = "Jeg er sulten"
                        },
                        new
                        {
                            Id = 39,
                            CourseId = 4,
                            EnglishText = "I am thirsty",
                            NorwegianText = "Jeg er tørst"
                        },
                        new
                        {
                            Id = 40,
                            CourseId = 4,
                            EnglishText = "The food is delicious",
                            NorwegianText = "Maten er deilig"
                        },
                        new
                        {
                            Id = 41,
                            CourseId = 5,
                            EnglishText = "Where is the nearest bus stop?",
                            NorwegianText = "Hvor er nærmeste busstopp?"
                        },
                        new
                        {
                            Id = 42,
                            CourseId = 5,
                            EnglishText = "How do I get to the train station?",
                            NorwegianText = "Hvordan kommer jeg til togstasjonen?"
                        },
                        new
                        {
                            Id = 43,
                            CourseId = 5,
                            EnglishText = "Is it far from here?",
                            NorwegianText = "Er det langt herfra?"
                        },
                        new
                        {
                            Id = 44,
                            CourseId = 5,
                            EnglishText = "Go straight ahead",
                            NorwegianText = "Gå rett frem"
                        },
                        new
                        {
                            Id = 45,
                            CourseId = 5,
                            EnglishText = "Turn left",
                            NorwegianText = "Ta til venstre"
                        },
                        new
                        {
                            Id = 46,
                            CourseId = 5,
                            EnglishText = "Turn right",
                            NorwegianText = "Ta til høyre"
                        },
                        new
                        {
                            Id = 47,
                            CourseId = 5,
                            EnglishText = "At the traffic lights, turn left",
                            NorwegianText = "Ved trafikklysene, ta til venstre"
                        },
                        new
                        {
                            Id = 48,
                            CourseId = 5,
                            EnglishText = "It’s next to the supermarket",
                            NorwegianText = "Det er ved siden av supermarkedet"
                        },
                        new
                        {
                            Id = 49,
                            CourseId = 5,
                            EnglishText = "It’s across the street",
                            NorwegianText = "Det er på den andre siden av gaten"
                        },
                        new
                        {
                            Id = 50,
                            CourseId = 5,
                            EnglishText = "Can you show me on the map?",
                            NorwegianText = "Kan du vise meg på kartet?"
                        },
                        new
                        {
                            Id = 51,
                            CourseId = 6,
                            EnglishText = "How much does this cost?",
                            NorwegianText = "Hvor mye koster dette?"
                        },
                        new
                        {
                            Id = 52,
                            CourseId = 6,
                            EnglishText = "Do you accept credit cards?",
                            NorwegianText = "Tar dere kredittkort?"
                        },
                        new
                        {
                            Id = 53,
                            CourseId = 6,
                            EnglishText = "I am just looking, thanks",
                            NorwegianText = "Jeg bare ser, takk"
                        },
                        new
                        {
                            Id = 54,
                            CourseId = 6,
                            EnglishText = "Can I try this on?",
                            NorwegianText = "Kan jeg prøve denne?"
                        },
                        new
                        {
                            Id = 55,
                            CourseId = 6,
                            EnglishText = "Do you have this in another size?",
                            NorwegianText = "Har dere denne i en annen størrelse?"
                        },
                        new
                        {
                            Id = 56,
                            CourseId = 6,
                            EnglishText = "Where is the changing room?",
                            NorwegianText = "Hvor er prøverommet?"
                        },
                        new
                        {
                            Id = 57,
                            CourseId = 6,
                            EnglishText = "I would like to buy this",
                            NorwegianText = "Jeg vil gjerne kjøpe denne"
                        },
                        new
                        {
                            Id = 58,
                            CourseId = 6,
                            EnglishText = "Can I get a receipt?",
                            NorwegianText = "Kan jeg få en kvittering?"
                        },
                        new
                        {
                            Id = 59,
                            CourseId = 6,
                            EnglishText = "Can I return this if it doesn’t fit?",
                            NorwegianText = "Kan jeg returnere denne hvis den ikke passer?"
                        },
                        new
                        {
                            Id = 60,
                            CourseId = 6,
                            EnglishText = "Do you have any discounts?",
                            NorwegianText = "Har dere noen rabatter?"
                        },
                        new
                        {
                            Id = 61,
                            CourseId = 7,
                            EnglishText = "What time is it?",
                            NorwegianText = "Hva er klokka?"
                        },
                        new
                        {
                            Id = 62,
                            CourseId = 7,
                            EnglishText = "It’s 3 o’clock",
                            NorwegianText = "Klokka er tre"
                        },
                        new
                        {
                            Id = 63,
                            CourseId = 7,
                            EnglishText = "It’s half past seven",
                            NorwegianText = "Klokka er halv åtte"
                        },
                        new
                        {
                            Id = 64,
                            CourseId = 7,
                            EnglishText = "It’s quarter to five",
                            NorwegianText = "Klokka er kvart på fem"
                        },
                        new
                        {
                            Id = 65,
                            CourseId = 7,
                            EnglishText = "It’s ten past nine",
                            NorwegianText = "Klokka er ti over ni"
                        },
                        new
                        {
                            Id = 66,
                            CourseId = 7,
                            EnglishText = "Today is Monday",
                            NorwegianText = "I dag er det mandag"
                        },
                        new
                        {
                            Id = 67,
                            CourseId = 7,
                            EnglishText = "My birthday is in July",
                            NorwegianText = "Bursdagen min er i juli"
                        },
                        new
                        {
                            Id = 68,
                            CourseId = 7,
                            EnglishText = "What day is it today?",
                            NorwegianText = "Hvilken dag er det i dag?"
                        },
                        new
                        {
                            Id = 69,
                            CourseId = 7,
                            EnglishText = "The meeting is on Friday",
                            NorwegianText = "Møtet er på fredag"
                        },
                        new
                        {
                            Id = 70,
                            CourseId = 7,
                            EnglishText = "I will arrive at 2 PM",
                            NorwegianText = "Jeg kommer klokka 14"
                        },
                        new
                        {
                            Id = 71,
                            CourseId = 8,
                            EnglishText = "Where is the airport?",
                            NorwegianText = "Hvor er flyplassen?"
                        },
                        new
                        {
                            Id = 72,
                            CourseId = 8,
                            EnglishText = "I need a taxi",
                            NorwegianText = "Jeg trenger en taxi"
                        },
                        new
                        {
                            Id = 73,
                            CourseId = 8,
                            EnglishText = "How much is a ticket to Oslo?",
                            NorwegianText = "Hvor mye koster en billett til Oslo?"
                        },
                        new
                        {
                            Id = 74,
                            CourseId = 8,
                            EnglishText = "I have a reservation",
                            NorwegianText = "Jeg har en reservasjon"
                        },
                        new
                        {
                            Id = 75,
                            CourseId = 8,
                            EnglishText = "Can I see your passport?",
                            NorwegianText = "Kan jeg se passet ditt?"
                        },
                        new
                        {
                            Id = 76,
                            CourseId = 8,
                            EnglishText = "What time is the flight?",
                            NorwegianText = "Når går flyet?"
                        },
                        new
                        {
                            Id = 77,
                            CourseId = 8,
                            EnglishText = "I need a hotel room",
                            NorwegianText = "Jeg trenger et hotellrom"
                        },
                        new
                        {
                            Id = 78,
                            CourseId = 8,
                            EnglishText = "Where is the train station?",
                            NorwegianText = "Hvor er togstasjonen?"
                        },
                        new
                        {
                            Id = 79,
                            CourseId = 8,
                            EnglishText = "Can you help me?",
                            NorwegianText = "Kan du hjelpe meg?"
                        },
                        new
                        {
                            Id = 80,
                            CourseId = 8,
                            EnglishText = "I am lost",
                            NorwegianText = "Jeg har gått meg bort"
                        },
                        new
                        {
                            Id = 81,
                            CourseId = 9,
                            EnglishText = "What do you do for a living?",
                            NorwegianText = "Hva jobber du med?"
                        },
                        new
                        {
                            Id = 82,
                            CourseId = 9,
                            EnglishText = "I work as a developer",
                            NorwegianText = "Jeg jobber som utvikler"
                        },
                        new
                        {
                            Id = 83,
                            CourseId = 9,
                            EnglishText = "I have a meeting at 10 AM",
                            NorwegianText = "Jeg har et møte klokka 10"
                        },
                        new
                        {
                            Id = 84,
                            CourseId = 9,
                            EnglishText = "Can we schedule a call?",
                            NorwegianText = "Kan vi avtale en samtale?"
                        },
                        new
                        {
                            Id = 85,
                            CourseId = 9,
                            EnglishText = "Please send me an email",
                            NorwegianText = "Vennligst send meg en e-post"
                        },
                        new
                        {
                            Id = 86,
                            CourseId = 9,
                            EnglishText = "Let's discuss this project",
                            NorwegianText = "La oss diskutere dette prosjektet"
                        },
                        new
                        {
                            Id = 87,
                            CourseId = 9,
                            EnglishText = "I need to submit a report",
                            NorwegianText = "Jeg må levere en rapport"
                        },
                        new
                        {
                            Id = 88,
                            CourseId = 9,
                            EnglishText = "When is the deadline?",
                            NorwegianText = "Når er fristen?"
                        },
                        new
                        {
                            Id = 89,
                            CourseId = 9,
                            EnglishText = "I work remotely",
                            NorwegianText = "Jeg jobber eksternt"
                        },
                        new
                        {
                            Id = 90,
                            CourseId = 9,
                            EnglishText = "Let's have a coffee break",
                            NorwegianText = "La oss ta en kaffepause"
                        },
                        new
                        {
                            Id = 91,
                            CourseId = 10,
                            EnglishText = "Help!",
                            NorwegianText = "Hjelp!"
                        },
                        new
                        {
                            Id = 92,
                            CourseId = 10,
                            EnglishText = "Call an ambulance!",
                            NorwegianText = "Ring etter en ambulanse!"
                        },
                        new
                        {
                            Id = 93,
                            CourseId = 10,
                            EnglishText = "I need a doctor",
                            NorwegianText = "Jeg trenger en lege"
                        },
                        new
                        {
                            Id = 94,
                            CourseId = 10,
                            EnglishText = "There has been an accident",
                            NorwegianText = "Det har vært en ulykke"
                        },
                        new
                        {
                            Id = 95,
                            CourseId = 10,
                            EnglishText = "Call the police!",
                            NorwegianText = "Ring politiet!"
                        },
                        new
                        {
                            Id = 96,
                            CourseId = 10,
                            EnglishText = "I lost my passport",
                            NorwegianText = "Jeg har mistet passet mitt"
                        },
                        new
                        {
                            Id = 97,
                            CourseId = 10,
                            EnglishText = "Where is the nearest hospital?",
                            NorwegianText = "Hvor er nærmeste sykehus?"
                        },
                        new
                        {
                            Id = 98,
                            CourseId = 10,
                            EnglishText = "I am feeling sick",
                            NorwegianText = "Jeg føler meg dårlig"
                        },
                        new
                        {
                            Id = 99,
                            CourseId = 10,
                            EnglishText = "Can you help me?",
                            NorwegianText = "Kan du hjelpe meg?"
                        },
                        new
                        {
                            Id = 100,
                            CourseId = 10,
                            EnglishText = "I need to contact my embassy",
                            NorwegianText = "Jeg må kontakte ambassaden min"
                        });
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedUnits")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Models.CourseCard", b =>
                {
                    b.HasOne("WebApi.Models.Course", "Course")
                        .WithMany("Cards")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WebApi.Models.Course", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
